### ISSUE TITLE
error showing

### ISSUE THREAD

**Issue by nimmalik001** [N0rz3/Phunter#15]
Traceback (most recent call last):
  File "C:\Users\HP\OneDrive\Documents\GitHub\Phunter\phunter.py", line 7, in <module>
    from lib.cli import parser
  File "C:\Users\HP\OneDrive\Documents\GitHub\Phunter\lib\cli.py", line 2, in <module>
    from .lookup import lookup
  File "C:\Users\HP\OneDrive\Documents\GitHub\Phunter\lib\lookup.py", line 1, in <module>
    import phonenumbers
ModuleNotFoundError: No module named 'phonenumbers'

**Comment by victormirandamx** [comment]
i have this error to
