### ISSUE TITLE
Issue running script

### ISSUE THREAD

**Issue by yakubsido21** [N0rz3/Phunter#7]
Traceback (most recent call last):
  File "C:\Users\User 1\Phunter\phunter.py", line 7, in <module>
    from lib.cli import parser
  File "C:\Users\User 1\Phunter\lib\cli.py", line 2, in <module>
    from .lookup import lookup
  File "C:\Users\User 1\Phunter\lib\lookup.py", line 4, in <module>
    from .reputation import *
  File "C:\Users\User 1\Phunter\lib\reputation.py", line 6, in <module>
    with open("useragents.txt", "r") as user:
FileNotFoundError: [Errno 2] No such file or directory: 'useragents.txt'

This is the messagei get when i run the script

**Comment by N0rz3** [comment]
hi, then check if the `useragents.txt` file is present in your directory
